version: '2'

networks:
  kafka-net:
    driver: bridge
  process_bus:
    driver: macvlan
    driver_opts:
      parent: eth0
  station_bus:
    driver: bridge

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server1:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server1:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
  #kafka-server2:
  #  image: 'bitnami/kafka:latest'
  #  networks:
  #    - kafka-net
  #  ports:
  #    - '9093:9092'
  #  environment:
  #    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
  #    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
  #    - ALLOW_PLAINTEXT_LISTENER=yes
  #  depends_on:
  #    - zookeeper-server

  cm:
    container_name: cm
    build:
      context: ./producer
    volumes:
      - "./producer:/acquisition_module"
      - "./libs:/acquisition_module/libs"
    networks:
      - process_bus
      - station_bus
      - kafka-net
    restart: unless-stopped
    privileged: true
    depends_on:
      - kafka-server1

  thirdlayer:
    container_name: thirdlayer
    build:
      context: ./consumer
    volumes:
      - "./consumer/:/consumer_module"
      - "./libs:/consumer_module/libs"
    networks:
      - station_bus
      - kafka-net
    restart: unless-stopped
    privileged: TRUE
    depends_on:
      - kafka-server1
      - cm
