version: '2'

networks:
  kafka-net:
    driver: bridge
  process_bus:
    driver: macvlan
    driver_opts:
      parent: eth0
  station_bus:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3.8.2-management
    container_name: rabbitmq
    ports:
      - 8080:15672
      - 5671:5671
      - 5672:5672
      - 25672:25672
    environment:
      - RABBITMQ_DEFAULT_USER=dam
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - station_bus
    restart: unless-stopped

  cm:
    container_name: cm
    build:
      context: ./producer
    volumes:
      - "./producer:/acquisition_module"
      - "./libs:/acquisition_module/libs"
    networks:
      - process_bus
      - station_bus
      - kafka-net
    restart: unless-stopped
    privileged: true
    depends_on:
      - rabbitmq

  thirdlayer1:
    container_name: thirdlayer1
    # build:
    #   context: ./thirdlayer1
    image: my-gcc-app
    volumes:
      # - "./consumer:/consumer_module/"
      - "./libs:/consumer_module/libs"
      - "./thirdlayer1/data:/consumer_module/data"
    networks:
      - station_bus
      - kafka-net
    restart: unless-stopped
    privileged: TRUE
    depends_on:
      - rabbitmq
      - cm
    
  thirdlayer2:
    container_name: thirdlayer2
    # build:
    #   context: ./thirdlayer2
    image: my-gcc-app
    volumes:
      # - "./consumer:/consumer_module/"
      - "./libs:/consumer_module/libs"
      - "./thirdlayer2/data:/consumer_module/data"
    networks:
      - station_bus
      - kafka-net
    restart: unless-stopped
    privileged: TRUE
    depends_on:
      - rabbitmq
      - cm
