version: '2'

networks:
  kafka-net:
    driver: bridge
  process_bus:
    driver: macvlan
    driver_opts:
      parent: eth0
  station_bus:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3.8.2-management
    container_name: rabbitmq
    ports:
      - 8080:15672
      - 5671:5671
      - 5672:5672
      - 25672:25672
    environment:
      - RABBITMQ_DEFAULT_USER=dam
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - station_bus
    restart: unless-stopped

  cm:
    container_name: cm
    build:
      context: ./producer
    volumes:
      - "./producer:/acquisition_module"
      - "./libs:/acquisition_module/libs"
    networks:
      - process_bus
      - station_bus
      - kafka-net
    restart: unless-stopped
    privileged: true
    depends_on:
      - rabbitmq

  rabbitmq-consumer1:
    container_name: rabbitmq-consumer1
    # build:
    #   context: ./thirdlayer1
    image: rabbitmq-gcc-consumer
    volumes:
      # - "./consumer:/consumer_module/"
      - "./libs:/consumer_module/libs"
      - "./rabbitmq_data/data:/consumer_module/data"
    networks:
      - station_bus
      - kafka-net
    restart: unless-stopped
    privileged: TRUE
    depends_on:
      - rabbitmq
      - cm
    
  # rabbitmq-consumer2:
  #   container_name: rabbitmq-consumer2
  #   # build:
  #   #   context: ./thirdlayer2
  #   image: rabbitmq-gcc-consumer
  #   volumes:
  #     # - "./consumer:/consumer_module/"
  #     - "./libs:/consumer_module/libs"
  #     - "./thirdlayer2/data:/consumer_module/data"
  #   networks:
  #     - station_bus
  #     - kafka-net
  #   restart: unless-stopped
  #   privileged: TRUE
  #   depends_on:
  #     - rabbitmq
  #     - cm
